### ISSUE TITLE
[Feat] 상세페이지 웹 연결

### ISSUE THREAD

**Issue by ckkim817** [GEON-PPANG/GEON-PPANG-iOS#182]
## 💡 Issue

상세페이지 웹 연결 구현을 위한 이슈입니다. (홈페이지, 인스타그램 등)
사실 구현은 아니고 있는 성민이 코드 쓰면 됩니다 ㄱㅅㄱㅅ

## 📝  Todo
- [ ] 상세페이지 웹 연결

**Comment by jeongdung-eo** [comment]
저기요 제가 다른 방법 말씀드렸잖아여 
`SFSafariViewController`
