### ISSUE TITLE
[Feat] 빵집 리스트뷰 구현

### ISSUE THREAD

**Issue by jeongdung-eo** [GEON-PPANG/GEON-PPANG-iOS#36]
## 💡 Issue
- 빵집 리스트뷰 구현을 위한 이슈입니다. 
## 📝  Todo
- [ ] 상단뷰 구현
- [ ] 필터 컬렉션뷰 구현
- [ ] 빵집리스트 컬렉션뷰 구현

**Comment by ckkim817** [comment]
이슈 title 수정해주세욤
